### ISSUE TITLE
publish unit test code coverage to Codecov

### ISSUE THREAD

**Issue by ericbuckley** [CDCgov/RecordLinker#32]
## Summary
At the end of our unit test CI job, we should publish the results of those runs to Codecov.  This will help us track our testing coverage over time, allow us to create rules so we don't add too much code that's not tested, and publicly display this information on the repo.

## Acceptance Criteria
- [ ] A codecov secret added to the repo
- [ ] A new last step on the unit test workflow that sends coverage results to Codedov

## Details / Tasks
- We'll need to first request adding the repo to Codecov as we can't do that ourselves.  We should create a [new issue in CDC's template repo](https://github.com/CDCgov/template/issues), with a request for [setting up Codecov](https://docs.codecov.com/docs/quick-start) on our RecordLinker repo
- I'm not sure how they'll share the secret with us, but maybe we can request they send us a DM over Teams?
- last we'll need to configure the [action](https://github.com/codecov/codecov-action) in our existing CI workflow

**Comment by derekadombek** [comment]
submitted an issue for access.
